# Generated by Django 5.1.15 on 2026-08-30 12:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('short_id', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=100)),
                ('classification', models.CharField(choices=[('RESTRICTED', 'Restricted'), ('CONFIDENTIAL', 'Confidential'), ('SECRET', 'Secret')], max_length=15)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('encryption', models.CharField(default='AES-256', max_length=20)),
                ('sha256', models.CharField(blank=True, max_length=128)),
                ('stored_hash', models.CharField(blank=True, max_length=128)),
                ('blockchain_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('MISMATCH', 'Mismatch')], default='PENDING', max_length=10)),
                ('integrity_status', models.CharField(choices=[('AUTHENTIC', 'Authentic'), ('TAMPERED', 'Tampered'), ('UNVERIFIED', 'Unverified')], default='UNVERIFIED', max_length=15)),
                ('custodian_role', models.CharField(blank=True, max_length=100)),
                ('size_pages', models.IntegerField(default=1)),
                ('file', models.FileField(blank=True, upload_to='encrypted_docs/')),
                ('extracted_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_set', to='cases.case')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'db_table': 'documents_document',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('current_stage', models.CharField(choices=[('upload', 'Upload'), ('ocr', 'OCR'), ('classify', 'Classify'), ('hash', 'SHA-256 Hash'), ('encrypt', 'AES-256 Encrypt'), ('store', 'Secure Storage'), ('blockchain', 'Blockchain Register'), ('complete', 'Complete'), ('failed', 'Failed')], default='upload', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline', to='documents.document')),
            ],
            options={
                'db_table': 'documents_pipeline_run',
            },
        ),
    ]
