# Generated by Django 5.1.15 on 2026-08-30 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseQAThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qa_thread', to='cases.case')),
            ],
            options={
                'db_table': 'ai_qa_thread',
            },
        ),
        migrations.CreateModel(
            name='CaseQAMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('sources', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.caseqathread')),
            ],
            options={
                'db_table': 'ai_qa_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contradiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('statements', models.JSONField(default=list)),
                ('finding', models.TextField()),
                ('status', models.CharField(default='Requires Human Review', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contradictions', to='cases.case')),
            ],
            options={
                'db_table': 'ai_contradiction',
            },
        ),
        migrations.CreateModel(
            name='DocumentInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('entities', models.JSONField(default=dict)),
                ('important_dates', models.JSONField(default=list)),
                ('findings', models.JSONField(default=list)),
                ('related_doc_names', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='documents.document')),
            ],
            options={
                'db_table': 'ai_document_insight',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGraphEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_node', models.CharField(max_length=20)),
                ('target_node', models.CharField(max_length=20)),
                ('relation', models.CharField(max_length=100)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kg_edges', to='cases.case')),
            ],
            options={
                'db_table': 'ai_kg_edge',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGraphNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=200)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kg_nodes', to='cases.case')),
            ],
            options={
                'db_table': 'ai_kg_node',
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('event', models.TextField()),
                ('source', models.CharField(max_length=200)),
                ('related_entity', models.CharField(blank=True, max_length=200)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='cases.case')),
            ],
            options={
                'db_table': 'ai_timeline_event',
                'ordering': ['id'],
            },
        ),
    ]
