# Generated by Django 5.1.15 on 2026-08-30 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('type', models.CharField(choices=[('Digital', 'Digital'), ('Document', 'Document'), ('Testimonial', 'Testimonial')], max_length=20)),
                ('description', models.TextField()),
                ('source', models.CharField(max_length=300)),
                ('custodian_role', models.CharField(max_length=100)),
                ('date_added', models.DateField()),
                ('integrity_status', models.CharField(default='AUTHENTIC', max_length=20)),
                ('blockchain_status', models.CharField(default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_set', to='cases.case')),
            ],
            options={
                'verbose_name': 'Evidence',
                'db_table': 'evidence_evidence',
                'ordering': ['-date_added'],
            },
        ),
    ]
