# Generated by Django 5.1.15 on 2026-08-30 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('evidence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_hash', models.CharField(max_length=128)),
                ('blockchain_hash', models.CharField(max_length=128)),
                ('action', models.CharField(default='Registration', max_length=50)),
                ('tx_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('prev_tx_id', models.CharField(blank=True, default='GENESIS', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockchain_records', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockchain_records', to='documents.document')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockchain_records', to='evidence.evidence')),
            ],
            options={
                'verbose_name': 'Blockchain Record',
                'db_table': 'blockchain_record',
                'ordering': ['-timestamp'],
            },
        ),
    ]
