# Generated by Django 5.1.15 on 2026-08-30 12:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Login Attempt',
                'db_table': 'accounts_login_attempt',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(choices=[('IO', 'Investigation Officer'), ('FA', 'Forensic Analyst'), ('LO', 'Legal Officer'), ('SO', 'Supervisory Officer'), ('SA', 'System Administrator')], default='IO', max_length=2)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('badge_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended')], default='Active', max_length=10)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'db_table': 'accounts_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PermissionMatrixEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('IO', 'Investigation Officer'), ('FA', 'Forensic Analyst'), ('LO', 'Legal Officer'), ('SO', 'Supervisory Officer'), ('SA', 'System Administrator')], max_length=2)),
                ('action', models.CharField(choices=[('Upload', 'Upload'), ('Download', 'Download'), ('Verify', 'Verify'), ('Custody Transfer', 'Custody Transfer'), ('Approve', 'Approve'), ('Manage', 'Manage')], max_length=20)),
                ('allowed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Permission Matrix Entry',
                'db_table': 'accounts_permission_matrix',
                'unique_together': {('role', 'action')},
            },
        ),
        migrations.CreateModel(
            name='RolePageAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('IO', 'Investigation Officer'), ('FA', 'Forensic Analyst'), ('LO', 'Legal Officer'), ('SO', 'Supervisory Officer'), ('SA', 'System Administrator')], max_length=2)),
                ('page_id', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Role Page Access',
                'db_table': 'accounts_role_page_access',
                'unique_together': {('role', 'page_id')},
            },
        ),
    ]
