# Generated by Django 5.1.15 on 2026-08-30 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True)),
                ('classification', models.CharField(choices=[('RESTRICTED', 'Restricted'), ('CONFIDENTIAL', 'Confidential'), ('SECRET', 'Secret')], max_length=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('UNDER REVIEW', 'Under Review'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=15)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_officers', models.ManyToManyField(blank=True, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case',
                'db_table': 'cases_case',
                'ordering': ['-created_date'],
            },
        ),
    ]
