# Generated by Django 5.1.15 on 2026-08-30 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustodyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type_label', models.CharField(default='document', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_custodian_role', models.CharField(default='—', max_length=100)),
                ('to_custodian_role', models.CharField(default='—', max_length=100)),
                ('verification_status', models.CharField(default='VERIFIED', max_length=20)),
                ('transfer_status', models.CharField(blank=True, choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_events', to='cases.case')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custody Event',
                'db_table': 'custody_event',
                'ordering': ['-timestamp'],
            },
        ),
    ]
