# Generated by Django 5.1.15 on 2026-08-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('WARNING', 'Warning'), ('INFO', 'Info'), ('RESOLVED', 'Resolved')], default='INFO', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('target', models.CharField(blank=True, max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER REVIEW', 'Under Review'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Security Alert',
                'db_table': 'alerts_security_alert',
                'ordering': ['-timestamp'],
            },
        ),
    ]
